### ISSUE TITLE
Questions about the license

### ISSUE THREAD

**Issue by chophilip21** [nightrome/cocostuff#24]
Hi, I am working for a start-up and we are training a segmentation model based on COCO-stuff dataset.

We are not re-distributing any of the COCO images, and we are simply using the images and annotations for training. Below is what I can find regarding licenses, but I am not too sure if using the models commercially will be any breach of the licenses for below.

```
COCO-Stuff is a derivative work of the COCO dataset. The authors of COCO do not in any form endorse this work. Different licenses apply:

COCO images: [Flickr Terms of use](http://cocodataset.org/#termsofuse)
COCO annotations: [Creative Commons Attribution 4.0 License](http://cocodataset.org/#termsofuse)
COCO-Stuff annotations & code: [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/legalcode)[](https://github.com/nightrome/cocostuff#acknowledgements)
```

**Comment by nightrome** [comment]
Hi, thank you for your interest. I will give you my personal and legally non-binding interpretation of the licenses. The COCO and COCO-Stuff annotations are under "Creative Commons Attribution 4.0 License", which "lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation" according to [this page](https://smartcopying.edu.au/quick-guide-to-creative-commons/#:~:text=Attribution%204.0%20%E2%80%93%20This%20licence%20lets,and%20use%20of%20licensed%20materials.).

Your problem will be with the images that fall under Flickr license. Training a Neural Network for commercial purposes will likely be interpreted as commercial use. Hence you would need to check for every single image whether its copyright holder (the person that took the photo) allowed commercial use. It's also not clear if you would even find those images and their license information anymore, since many may have already been deleted.
